### ISSUE TITLE
Specify intended PLC host, in DID document?

### ISSUE THREAD

**Issue by DavidBuchanan314** [did-method-plc/did-method-plc#33]
Problem: There's nothing stopping sandbox-network DIDs from being mirrored into prod, and vice versa.

There are other reasons you might want to partition off a "parallel universe" atproto network, without worrying about things inadvertently (or maliciously) leaking from one network to another.

Per the docs, the DID document enumerates services associated with the DID:

```js
services: {
    atproto_pds: {
      type: "AtprotoPersonalDataServer",
      endpoint: "https://example.test"
    }
}
```

What if there was another service type, to describe the intended PLC host? Something along the lines of

```js
did_plc_host: {
    type: "DidPlcDirectoryServer",
    endpoint: "https://plc.directory/"
}
```

A PLC instance may still allow itself to "re-host" foreign DIDs, or those with an unspecified PLC host (i.e. every currently existing record), but it can choose to denylist certain PLC hosts (such as known sandbox instances)

**Comment by bnewbold** [comment]
We have a whole bunch of existing DIDs in prod which don't have this kind of metadata, and I don't think we want to allow those to migrate to/from sandbox like they can today.

A general version of this would be some kind of flag in the genesis operation which indicates permanently that a DID is sandbox-specific (or any non-default / non-public environment). Because it is in the genesis block, it can't be expunged later. Adding a special `services` endpoint as you propose above would be one way to flag it. It isn't possible to set up a DID in a PLC directory without the full history, so it wouldn't be hard to enforce this in code. did:web will always be able to flip/flop around between environments though.

As some background, we did spend some time trying to come up with a way to indelibly mark DIDs as sandbox-or-not when rolling out sandbox, and even considered `did:plc-sandbox:` or `did:plc:sandbox:` as special prefixes, but decided this would require implementation flexibility/complexity too deep in the stack.

**Comment by DavidBuchanan314** [comment]
closing this because there's no more sandbox 😅
