### ISSUE TITLE
plc.directory permits operations to contain arbitrary fields but fails to subsequently derive DID documents

### ISSUE THREAD

**Issue by str4d** [did-method-plc/did-method-plc#71]
plc.directory stores the PLC operation for a given log entry directly as JSON in its database:
https://github.com/did-method-plc/did-method-plc/blob/8132e197b7c55421aac923de11a934f8d36d7387/packages/server/src/migrations/20230223T215019669Z-refactor.ts#L7

However, the JSON is not validated to only contain expected fields. This means that the `operation` object can contain arbitrary additional fields beyond what the DID PLC specification requires (subject to the max byte size limit on the encoded operation). These arbitrary fields need to be preserved in order to re-derive CIDs and validate signatures.

If this is intentional behaviour, it needs to be documented in the DID PLC specification. If it is not, then changes should probably be made to reject these records.

Assuming this is intentional behaviour, there is a further problem: currently you can create DIDs containing arbitrary extra fields, but you cannot _use_ them because the DID document does not resolve. Attempting to call the `/<DID>` or `/<DID>/data` endpoints for such a DID results in an HTTP 500 Internal Server Error. (The `/<DID>/log[/*]` endpoints all work fine, as does `/export` when exporting the log entries for the DID.)

The following DIDs (all helpfully contributed to the PLC directory by @DavidBuchanan314) each have just a create `plc_operation`, containing a single arbitrary extra field, and cause plc.directory to display the above behaviour:
- `did:plc:hotzvqdvfcpkhwdfwsqmnzdd`
- `did:plc:lyzhshvwhbb43ilfthirfbyw`
- `did:plc:p4y6z2ruhg4tao7kwnng3wag`
- `did:plc:jcouh25wx4pr3lte5f2ss3r2`
- `did:plc:dava3c6rbkms6nn5jbieso6j`
- `did:plc:smxazsapwnzadndupdcwduzv`
- `did:plc:aneosvncwerovrzwxrmrnurv`
- `did:plc:f3qyyf2mdveuqwgtzt6tcp4w`
- `did:plc:2dv6vvjx6tf3zsibedq5xtpp`
- `did:plc:ag3gatteub5k23e7ivqb5k5t`

**Comment by DavidBuchanan314** [comment]
oops :sweat_smile:

**Comment by str4d** [comment]
Another slightly more annoying example is `did:plc:m7ao6mg35yfcc4m6h6662k2h`, which has this operation in its history:
```json
{
  "did": "did:plc:m7ao6mg35yfcc4m6h6662k2h",
  "operation": {
    "sig": "qnEMbNBq49fqOVKrCTiX4286-35dAYzEuewn7yKLK1NzdZ6cJOhFEQO0VG8A6MfHOxGAyf_wuQQlovBoPis2Sw",
    "prev": "bafyreidhydxtbw7obiqxdhr7xxwswr2s7gwuwe4stxcij4ugusnhynetbi",
    "type": "plc_operation",
    "services": {
      "atproto_pds": {
        "type": "AtprotoPersonalDataServer",
        "endpoint": "https://porcini.us-east.host.bsky.network"
      },
      "boop_instance_verification:": {
        "test": "best",
        "type": "BoopInstanceVerification",
        "endpoint": "https://localhost:8080/"
      }
    },
    "alsoKnownAs": [
      "at://besttest.bsky.social"
    ],
    "rotationKeys": [
      "did:key:zQ3shhCGUqDKjStzuDxPkTxN6ujddP4RkEKJJouJGRRkaLGbg",
      "did:key:zQ3shpKnbdPx3g3CmPf5cRVTPe1HtSwVn5ish3wSnDPQCbLJK"
    ],
    "verificationMethods": {
      "atproto": "did:key:zQ3shqMW9GQhhZb6JMcycHkYrU1mRp6NGKzgUvYeU7Kj2d6hp"
    }
  },
  "cid": "bafyreieifhtf2wsdx7j4hxja5r4tckxd6bgfynz3koicjhswat4hvsk62y",
  "nullified": false,
  "createdAt": "2024-04-02T14:54:17.307Z"
}
```

Note the arbitrary map key under `services`, which exercises an ambiguity in the specification (where it does not specify that `type` and `endpoint` are the _only_ keys allowed):
https://github.com/did-method-plc/did-method-plc/blob/8132e197b7c55421aac923de11a934f8d36d7387/README.md?plain=1#L25

The DID was updated about half an hour later to remove the test field, but its presence in the registry now forces all PLC operators to handle it for every operation. The DID PLC spec should be updated to clarify if this is permitted going forward.

The only other place in the `operation` JSON where arbitrary keys could occur is `verificationMethods`, but that is specified as an object containing `string` keys and `did:key` values, so *hopefully* plc.directory is validating all entries in that object...

**Comment by bnewbold** [comment]
Thanks for reporting this!

Have not dug in deeply yet, but my initial reaction is that this is Bad, should not be allowed, and we may need to do surgery/cleanup to remove those DIDs/ops from the directory. That is a strong intervention which we don't take lightly, so will need to consult with the team and do comms around this.

But for now would ask that folks not make such ops, and/or warn that they may be rejected in the future or even retroactively removed the the directory.

We should probably be more carefully de-serializing/re-serializing content on the write path, instead of just validating provided JSON. We also need implementation-neutral / language-neutral test vectors so we can create interoperable test vectors for this kind of corner case.

**Comment by DavidBuchanan314** [comment]
I believe the failure to resolve is actually a regression.

When I made this post https://bsky.app/profile/did:plc:vwzwgnygau7ed7b7wt5ux7y2/post/3jw2hn5dm7m2e (May 2023), I'm quite confident that https://plc.directory/did:plc:aneosvncwerovrzwxrmrnurv resolved and returned a DID document, rather than erroring.

(now you can only see the audit log, https://plc.directory/did:plc:aneosvncwerovrzwxrmrnurv/log/audit )
